cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 0 max-rate 15 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 1 max-rate 22 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 2 max-rate 33 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 3 max-rate 44 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 4 max-rate 55 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 5 max-rate 66 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 6 max-rate 78 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 7 max-rate 89 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 8 max-rate 91 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 9 max-rate 10 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 10 max-rate 20 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 11 max-rate 30 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 12 max-rate 40 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 13 max-rate 50 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 14 max-rate 60 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 0 class 15 max-rate 70 pkt-size 1460

cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 0 max-rate 80 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 1 max-rate 90 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 2 max-rate 100 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 3 max-rate 10 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 4 max-rate 20 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 5 max-rate 30 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 6 max-rate 45 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 7 max-rate 51 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 8 max-rate 63 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 9 max-rate 74 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 10 max-rate 80 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 11 max-rate 90 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 12 max-rate 20 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 13 max-rate 21 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 14 max-rate 22 pkt-size 1460
cxgbtool enp129s0f4  sched-class  params type packet level cl-rl mode class rate-unit bits rate-mode relative  channel 1 class 15 max-rate 10 pkt-size 1460
